" Als erstes pathogen installieren
" http://www.vim.org/scripts/script.php?script_id=2332
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" No Compatibility... 2010
set nocompatible
set backspace=indent,eol,start

" Buffer wechseln ohne zu speicher ist ok
set hidden

" Vervollständigen wie bei der Bash mit Tab und langer Liste
set wildmenu
set wildmode=list:longest,full

" Alte Befehle soll er sich merken
set history=1000

" Der Leader-Key ist das Komma bei mir
let mapleader = ','

" Ich habe eine Maus...
set mouse=a

" Mit Zeilennummern
set number
set tabstop=4
set shiftwidth=4
set smarttab
set expandtab
set softtabstop=4
set autoindent

" Mindestens drei Zeilen noch anzeigen beim Scrollen
set scrolloff=3

" Für die Suche
set hlsearch
set incsearch
set ignorecase
set smartcase

" Einrückung
if has("autocmd")
    filetype plugin indent on
endif

" Vor dem Einfügen von formatierten Text
set pastetoggle=<F2>

" Mit F4 wird die Suche nicht mmehr hervorgehoben
noremap <F4> :set hlsearch! hlsearch?<CR>

" Temporäre Dateien sollen woanders liegen, nicht in den Projekten
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

" einfaches Wechseln der Buffer
nmap <silent> <F9> :bn<CR>
nmap <silent> <F10> :bp<CR>

" F8 macht tabs zu whitespaces, entfernt unnütze ws am Ende der Zeile
nnoremap <silent> <F8> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>:retab<CR>

let g:netrw_list_hide='^\.,.\(pyc\|pyo\|o\)$'

" mit w!! kann man auch als root Dateien speichern
cmap w!! w !sudo tee % >/dev/null

" Um Leerzeichen usw. anzuzeigen, kann man umschalten mit leader+s
nmap <leader>s :set list!<CR>
set listchars=tab:▸\ ,eol:¬

" NERDTree
" http://www.vim.org/scripts/script.php?script_id=1658
nnoremap <leader>t :NERDTreeToggle<CR>
let NERDTreeIgnore=['\~$', '\.pyc$', '\.pyo$', '\.class$', 'pip-log\.txt$', '\.o$']

" Snipmate
" http://www.vim.org/scripts/script.php?script_id=2540
" und zu 99% benutze iyh django ;-)
autocmd FileType python set ft=python.django
autocmd FileType html set ft=htmldjango.html

" ack-grep ist fast besser als Dominosteine
" http://betterthangrep.com/
" http://github.com/mileszs/ack.vim
" Fur Debian / Ubuntu
let g:ackprg="ack-grep -H --nocolor --nogroup --column"
nnoremap <leader>a :Ack

" Command-T https://wincent.com/products/command-t
" liegt per default auf leader-t
nnoremap <leader>o :CommandT<CR>

" taglist erkennt via ctags Funktionen usw
" Benötigt exuberant ctags !!
" apt-get install exuberant-ctags
let Tlist_Exit_OnlyWindow = 1     " exit if taglist is last window open
let Tlist_Show_One_File = 1       " Only show tags for current buffer
let Tlist_Enable_Fold_Column = 0  " no fold column (only showing one file)
nmap <silent> <leader>f :TlistToggle<CR>

